spring:
  datasource:
    url: jdbc:mariadb://mariadb:3306/user
    username: root
    password: '{cipher}AQBe1VoCVxUNjmyYcUcgLnEgSXLzjZO5lIUBknUxm9K4Ips2aBBNw9djMlWdHsWkbYlYMPYrpRHIyqc+LIpuq0Zk4Z90fXExZwqG5K6TekKQzjBGpGCpZ5FQd1gCxdeAGBTRKNy3G8WIZmnR8nu2QwhyBMf80aSgxC6gvpi4H3IhJqbj2c7/Bl7rdFHEXsm7xYkHdRSGgga09JpMDMSFWKg/v0t2xnQYBzyj2eSBNCO9qljN5Pbh8F6e+Xwml631WGzrse2TcuVAN0hbtzN4osGqpkhQpKNiqexh/SAliwZ0EIAC4fMS6greEd+s4nWaOl/VOducOJYDngr9QMiGTTVKGGSWB8WyxNcVV7lxQ8umXUxVT/ljCJ7tCww85qaTc/c='
    driver-class-name: org.mariadb.jdbc.Driver
    #mysql
    #driver-class-name: com.mysql.cj.jdbc.Driver
    #url: jdbc:mysql://127.0.0.1:3306/msa
    #username: root
    #password: '{cipher}AQAKW/LhLaTWn5FTKujfM1DferMea/dvoix9dRPu+ZUinxmCQRNaf/Ip//dAATslqR/apRoMWiLt7Q6wJ9AownZBz2FTPlB7otMeapQ5v85TU9z119hGMwtuGXE20O25VPkCdNBXIQuccI4zoOXMxAOTDBZ8ABk1KD7N0qmEHGJbCjx93GXdTWXVPSPzqeKJCEjPECcIvdbZbmWuFbMkwqt58VW2zqrLjsG7xjZDYhSVhaMDlAytv58wVfesXZUS8ck00djPECQkCFLuJgXAmsVjWPl7TMNBxpt2jR0zhNroSCs8WF+WVI47Gsy40sNW1nEMcAkShtfw0OMTi7l4fXmD04AF+HPZwCMu2YnrEJhjb/gLsEhQUP+DnS/On1TVgAE=' # cipher를 추가하여 해당 글자는 암호화 됐다는것을 명시
token: 
  expiration_time: 86400000
  secret: '{cipher}AQApUm/pYrDM4f1Wqfb0lN6ZkjlFz4wK8a7HXovonxnkm6pf4ZjghcDCfi+pBkzFuZmsiFQBo2zn0BGfaGjDbIC5i0TxA87t3FQVLbpExsVfzN/tIgkNJonkA0zctNSdeNayFO6ZoJHIE36ddrdDNjBfzAz4p9EkMjI1ilQ9q3OfAOmYgtcf/iM8viS+VWR9PNePKGq5UJ1fNwbdKt6s0kwj+6IAKGRNy9vDNu3f4eoyqQaj+dnUqesLuTc+T+qlHNVNPqhy9eFBsS1ZmaIJz6TMTSQydCGVBupfUsT2Glkp4GEBcwNMV19dGjMZdYIHzPSnNUIEMwEw8VLtzBwVmH16OOAVCpBCQy3KqxLJNINbrBqv18LXzWadg76G2MXIhcfeoAp5bO6GKjFGXc0tthtW'

# 127.0.0.1:9000 -> api-gateway 주소
order_service:
    #유레카에 등록된 이름  restTemplete의 loadBalanced이용
        url: http://ORDER-SERVICE/order-service/%s/orders
        # 에러처리
        exception:
           order_is_empty: User's orders is empty1. 

gateway:
  ip: 172.18.0.5